version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: franciscoalves90/barber-appoint:v1
    container_name: api-barber-appoint
    restart: always
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production

  # db:
  #   image: postgres:15-alpine
  #   container_name: api-db
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: nest_api
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:
